### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by friesey** [openpreserve/jhove#179] opened 2017-01-05 11:42 UTC
## Dev Effort
2D

## Description
Hi folks,

I use JHOVE as a library within own java code and run into a problem. 
File sm2-3ca2fd64c710a30edb60987e74d405cf from the IMageTestSuite cannot be worked on. The JHOVE GUI just stay silent (does nothing when the file is dragged and dropped onto it).

My java version of JHOVE gives this error:  "java.lang.NegativeArraySizeException" and does not stop. If the file is among other files, the whole process stopps and cannot be finished.

I hope this helps analysing the error. At least the information should be printed and JHOVE should continue with the next file instead of just hang itself.

Best, Yvonne

**Comment by friesey** [comment] 2017-01-05 11:55
File "m3-b0d36ed02fc2624ac79d3144e8b1bda2" has the exact same problem. 
btw, the file "sm2-3ca2fd64c710a30edb60987e74d405cf" is now named "m2-3ca2fd64c710a30edb60987e74d405cf", I do not know why there is an "s-prefix" in my older version of the testuite.
Best

**Comment by carlwilson** [comment] 2019-10-23 04:05
I can confirm that this is still an issue and is caused by [this method](https://github.com/openpreserve/jhove/blob/integration/jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ModuleBase.java#L1057) returning a negative number despite the lack of signing....

**Comment by tledoux** [comment] 2019-10-23 10:09
Hi @carlwilson, in fact the method readUnsignedInt works well and returns a long value in order to have enough space to handle large values.
In the example provided we have:
`Read STRIPOFFSETS count 3288334337 in int -1006632959 is BigEndian false`

However, the `count` value is casted as a `int` each time an `array` needs to be instanciate, for example
        `long [] array = new long [(int) count];`

In Java, arrays cannot be larger than `Integer.MAX_VALUE` (2^31-1). So I added a new check (checkCountArray) that is called each time an array will be instanciated to read the value.

This time the file ended with:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jhove xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schem
a.openpreservation.org/ois/xml/ns/jhove" xsi:schemaLocation="http://schema.openp
reservation.org/ois/xml/ns/jhove https://schema.openpreservation.org/ois/xml/xsd
/jhove/1.8/jhove.xsd" name="Jhove" release="1.23.0-SNAPSHOT" date="2019-10-23">
 <date>2019-10-23T11:07:10+02:00</date>
 <repInfo uri="v:%5CCorpusDeTest%5Ctif%5Cm2-3ca2fd64c710a30edb60987e74d405cf.tif
">
  <reportingModule release="1.9.1" date="2019-04-17">TIFF-hul</reportingModule>
  <lastModified>2009-02-03T14:36:06+01:00</lastModified>
  <size>54729</size>
  <format>TIFF</format>
  <status>Not well-formed</status>
  <sigMatch>
  <module>TIFF-hul</module>
  </sigMatch>
  <messages>
   <message subMessage="Type = 160, Tag = 474" offset="72" severity="error" id="TIFF-HUL-3">Unknown data type</message>
   <message offset="82" severity="error" id="TIFF-HUL-2">Tag 8 out of sequence</message>
   <message subMessage="Type = 0, Tag = 8" offset="84" severity="error" id="TIFF-HUL-3">Unknown data type</message>
   <message offset="94" severity="error" id="TIFF-HUL-2">Tag 1 out of sequence</message>
   <message subMessage="Type = 0, Tag = 1" offset="96" severity="error" id="TIFF-HUL-3">Unknown data type</message>
   <message severity="error"  id="TIFF-HUL-6">Count mismatch for tag 273; expecting 2147483647, saw 3288334337</message>
  </messages>
  <mimeType>image/tiff</mimeType>
 </repInfo>
</jhove>
```
The file is indeed not well-formed and badly corrupted...

**Closed as completed** 2019-12-10 03:02 UTC
Labels: bug, P2
