### ISSUE TITLE
Font list in Epub reporting module should be of type Array

### ISSUE THREAD

**Issue by samalloing** [openpreserve/jhove#676] opened 2021-05-21 15:05 UTC
The epub module reports a font list as a type of Set, when we automatically process the XML report for example Sets are processed as non repeatable fields. What happens is that only one entry of the fonts is stored in our system. I think the processing in our system is correct and that the font list should be of type Array (like Resources is).

https://github.com/openpreserve/jhove/blob/integration/jhove-ext-modules/src/main/java/org/ithaka/portico/jhove/module/EpubModule.java#L368 should be changed to type String[] so the output will be of Arity Array instead of Set.
`
<property>
     <name>Fonts</name>
     <values arity="Set" type="Property">
  ...
    </property>
`
cc @rosetta-format-library

**Comment by karenhanson** [comment] 2021-05-21 18:33
I took a look at this to try to retrace my decision to use Set over the other arities. In general I would expect Set to contain multiple values in a Java context. It's similar to an Array but does not support duplicate entries. According to [this documentation](https://jhove.openpreservation.org/javadoc/index.html?edu/harvard/hul/ois/jhove/class-use/PropertyArity.html), the Set arity maps to `java.util.Set`, which matches my understanding - a collection without duplicates. I probably used a Set within a Set because there should not be duplicate font records listed and there should not be duplicate entries on the font records (the font names showing up twice, for example). That's not to say it was the best decision - now that I'm looking at the other modules I see Set isn't used much in this sort of arrangement - Array or List is used more often. Also, if using Array, we couldn't use String[] as there are two sub-properties nested in the font property - one for font name and the other a boolean to indicate whether the font is embedded.

Maybe someone could verify that I'm understanding the use of these arities correctly and confirm whether this should be changed? For extra context, the EPUB [representation info is here](https://jhove.openpreservation.org/modules/third-party/epub/#repinfo) - noting now there is an extra "s" on one of the "fonts" that I'm about to go fix! I also took a screenshot of the arrangement being referred to:
![image](https://user-images.githubusercontent.com/4070836/119174115-2ebbec00-ba36-11eb-87d8-a0f432a7c850.png)

**Comment by carlwilson** [comment] 2022-06-16 15:10
@samalloing do you believe that this is a bug as such and that there may be a reason to have repeat entries? I ask because if that's the case then Set is quite clearly the wrong construct. The nature of the issue isn't quite clear to me.

**Comment by samalloing** [comment] 2022-06-17 10:08
Hi Carl,

I understand the reasoning of Karen. I think there shouldn't be duplicated entries. But I don't know if Set is the correct construct. I see in PDF for example that it there is no Set used. Because in our software only the first entry is shown when a Set is processed. I was wondering if Set was correct here and if it shouldn't be different like other modules (but ePub could be right and the rest wrong). Karen also made this observation in her post

I hope  made myself more clear now.

Sam

**Comment by carlwilson** [comment] 2023-06-13 20:53
Hi, @samalloing. I'm doing a bit of triage and have come back to this. My feeling is that the processing software should treat Sets like any other collection type. The Set only protects against genuine duplicates, but it's still a collection and can have multiple entries. I've started to move to Sets for other purposes, again with the aim of eliminating duplicate entries without writing code to do so. If this is a real problem there might be a compromise solution by converting the set to an array but that shouldn't be necessary.

**Comment by samalloing** [comment] 2023-06-14 06:53
Hi Carl,

Thanks for getting back on this. I think you are right. Great to see that other parts of the code are getting changed to sets as well.

Thanks for thinking on this with me. This gives me more insight in the workings of jHove!

Sam

**Comment by carlwilson** [comment] 2023-06-14 08:29
Not a problem Sam, closing this now.

**Closed as completed by carlwilson** 2023-06-14 08:29 UTC
Labels: bug, P1, OAG
