### ISSUE TITLE
False positive PDF-HUL-94 java.lang.NullPointerException

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#809] opened 2023-01-02 12:44 UTC
The attached file throws a PDF-HUL-94 NullPointerException but seems to be syntactially ok.
Cross-checked the file with Preflight, qpdf and pdfcpu. 
Pdfcpu did report an error for the /Tabs entry in the PagesDictionary as /Tabs is not supported with the claimed PDF version 1.4 of the file ... however, since JHOVE should only check agianst the 1.7 ISO spec, and is not version-feature-exact for anything y 1.7 this shouldn't make a difference,

Due to no futher info on the validation error and due to no negative results with other tools I consider this currently a false positive.

[algenreportNordsee_06082021.pdf](https://github.com/openpreserve/jhove/files/10331625/algenreportNordsee_06082021.pdf)

**Comment by asciim0** [comment] 2023-01-02 14:34
There's apparently no relation between the /Tabs entry and the NullPointer. If someone can let me know what check triggers the NullPointer exception, I can maybe pinpoint the error a little bit from there.

**Comment by samalloing** [comment] 2023-01-11 14:56
Hi @asciim0 

This problem is solved in the next relase of jHove 1.28. The problem is that Subject and Keyword are empty (null). That nullPointerException is handled now (see https://github.com/openpreserve/jhove/pull/782)

Sam

**Comment by asciim0** [comment] 2023-01-11 18:36
Awesome, thanks Sam! Will crosscheck with 1.28.

**Comment by carlwilson** [comment] 2023-01-13 10:30
Hi both, I've created a new version of this PR #820, which I think is safer but achieves its aims in less code. @asciim0 I've added your test file to the regression corpus and can confirm that the fix means it's now Well-formed and valid. @samalloing could you take a look at #820 and let me know what you think. Once it's merged I'll put a link to a test build here.

**Closed as completed** 2023-01-13 12:23 UTC
